(cl:defpackage my_service-srv
  (:use )
  (:export
   "QUADRATICSOLUTION"
   "<QUADRATICSOLUTION-REQUEST>"
   "QUADRATICSOLUTION-REQUEST"
   "<QUADRATICSOLUTION-RESPONSE>"
   "QUADRATICSOLUTION-RESPONSE"
  ))

