// Generated by gencpp from file my_service/QuadraticSolutionRequest.msg
// DO NOT EDIT!


#ifndef MY_SERVICE_MESSAGE_QUADRATICSOLUTIONREQUEST_H
#define MY_SERVICE_MESSAGE_QUADRATICSOLUTIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_service
{
template <class ContainerAllocator>
struct QuadraticSolutionRequest_
{
  typedef QuadraticSolutionRequest_<ContainerAllocator> Type;

  QuadraticSolutionRequest_()
    : a(0.0)
    , b(0.0)
    , c(0.0)  {
    }
  QuadraticSolutionRequest_(const ContainerAllocator& _alloc)
    : a(0.0)
    , b(0.0)
    , c(0.0)  {
  (void)_alloc;
    }



   typedef float _a_type;
  _a_type a;

   typedef float _b_type;
  _b_type b;

   typedef float _c_type;
  _c_type c;





  typedef boost::shared_ptr< ::my_service::QuadraticSolutionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_service::QuadraticSolutionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct QuadraticSolutionRequest_

typedef ::my_service::QuadraticSolutionRequest_<std::allocator<void> > QuadraticSolutionRequest;

typedef boost::shared_ptr< ::my_service::QuadraticSolutionRequest > QuadraticSolutionRequestPtr;
typedef boost::shared_ptr< ::my_service::QuadraticSolutionRequest const> QuadraticSolutionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_service::QuadraticSolutionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_service::QuadraticSolutionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_service::QuadraticSolutionRequest_<ContainerAllocator1> & lhs, const ::my_service::QuadraticSolutionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a &&
    lhs.b == rhs.b &&
    lhs.c == rhs.c;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_service::QuadraticSolutionRequest_<ContainerAllocator1> & lhs, const ::my_service::QuadraticSolutionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_service

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_service::QuadraticSolutionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_service::QuadraticSolutionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_service::QuadraticSolutionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_service::QuadraticSolutionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_service::QuadraticSolutionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_service::QuadraticSolutionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_service::QuadraticSolutionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d20f63a7e99cd5689c2dcf93cf2f8085";
  }

  static const char* value(const ::my_service::QuadraticSolutionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd20f63a7e99cd568ULL;
  static const uint64_t static_value2 = 0x9c2dcf93cf2f8085ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_service::QuadraticSolutionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_service/QuadraticSolutionRequest";
  }

  static const char* value(const ::my_service::QuadraticSolutionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_service::QuadraticSolutionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 a\n"
"float32 b\n"
"float32 c\n"
;
  }

  static const char* value(const ::my_service::QuadraticSolutionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_service::QuadraticSolutionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.b);
      stream.next(m.c);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct QuadraticSolutionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_service::QuadraticSolutionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_service::QuadraticSolutionRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<float>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<float>::stream(s, indent + "  ", v.b);
    s << indent << "c: ";
    Printer<float>::stream(s, indent + "  ", v.c);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_SERVICE_MESSAGE_QUADRATICSOLUTIONREQUEST_H
