// Generated by gencpp from file my_service/QuadraticSolution.msg
// DO NOT EDIT!


#ifndef MY_SERVICE_MESSAGE_QUADRATICSOLUTION_H
#define MY_SERVICE_MESSAGE_QUADRATICSOLUTION_H

#include <ros/service_traits.h>


#include <my_service/QuadraticSolutionRequest.h>
#include <my_service/QuadraticSolutionResponse.h>


namespace my_service
{

struct QuadraticSolution
{

typedef QuadraticSolutionRequest Request;
typedef QuadraticSolutionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct QuadraticSolution
} // namespace my_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_service::QuadraticSolution > {
  static const char* value()
  {
    return "58fcd0a6ce46cd18570e38efc5525a55";
  }

  static const char* value(const ::my_service::QuadraticSolution&) { return value(); }
};

template<>
struct DataType< ::my_service::QuadraticSolution > {
  static const char* value()
  {
    return "my_service/QuadraticSolution";
  }

  static const char* value(const ::my_service::QuadraticSolution&) { return value(); }
};


// service_traits::MD5Sum< ::my_service::QuadraticSolutionRequest> should match
// service_traits::MD5Sum< ::my_service::QuadraticSolution >
template<>
struct MD5Sum< ::my_service::QuadraticSolutionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::my_service::QuadraticSolution >::value();
  }
  static const char* value(const ::my_service::QuadraticSolutionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_service::QuadraticSolutionRequest> should match
// service_traits::DataType< ::my_service::QuadraticSolution >
template<>
struct DataType< ::my_service::QuadraticSolutionRequest>
{
  static const char* value()
  {
    return DataType< ::my_service::QuadraticSolution >::value();
  }
  static const char* value(const ::my_service::QuadraticSolutionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_service::QuadraticSolutionResponse> should match
// service_traits::MD5Sum< ::my_service::QuadraticSolution >
template<>
struct MD5Sum< ::my_service::QuadraticSolutionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::my_service::QuadraticSolution >::value();
  }
  static const char* value(const ::my_service::QuadraticSolutionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_service::QuadraticSolutionResponse> should match
// service_traits::DataType< ::my_service::QuadraticSolution >
template<>
struct DataType< ::my_service::QuadraticSolutionResponse>
{
  static const char* value()
  {
    return DataType< ::my_service::QuadraticSolution >::value();
  }
  static const char* value(const ::my_service::QuadraticSolutionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_SERVICE_MESSAGE_QUADRATICSOLUTION_H
