// Generated by gencpp from file my_service/QuadraticSolutionResponse.msg
// DO NOT EDIT!


#ifndef MY_SERVICE_MESSAGE_QUADRATICSOLUTIONRESPONSE_H
#define MY_SERVICE_MESSAGE_QUADRATICSOLUTIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_service
{
template <class ContainerAllocator>
struct QuadraticSolutionResponse_
{
  typedef QuadraticSolutionResponse_<ContainerAllocator> Type;

  QuadraticSolutionResponse_()
    : result()  {
    }
  QuadraticSolutionResponse_(const ContainerAllocator& _alloc)
    : result(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::my_service::QuadraticSolutionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_service::QuadraticSolutionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct QuadraticSolutionResponse_

typedef ::my_service::QuadraticSolutionResponse_<std::allocator<void> > QuadraticSolutionResponse;

typedef boost::shared_ptr< ::my_service::QuadraticSolutionResponse > QuadraticSolutionResponsePtr;
typedef boost::shared_ptr< ::my_service::QuadraticSolutionResponse const> QuadraticSolutionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_service::QuadraticSolutionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_service::QuadraticSolutionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_service::QuadraticSolutionResponse_<ContainerAllocator1> & lhs, const ::my_service::QuadraticSolutionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_service::QuadraticSolutionResponse_<ContainerAllocator1> & lhs, const ::my_service::QuadraticSolutionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_service

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_service::QuadraticSolutionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_service::QuadraticSolutionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_service::QuadraticSolutionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_service::QuadraticSolutionResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_service::QuadraticSolutionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_service::QuadraticSolutionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_service::QuadraticSolutionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3c22c54177823ce2fb183c378e2b071c";
  }

  static const char* value(const ::my_service::QuadraticSolutionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3c22c54177823ce2ULL;
  static const uint64_t static_value2 = 0xfb183c378e2b071cULL;
};

template<class ContainerAllocator>
struct DataType< ::my_service::QuadraticSolutionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_service/QuadraticSolutionResponse";
  }

  static const char* value(const ::my_service::QuadraticSolutionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_service::QuadraticSolutionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] result\n"
;
  }

  static const char* value(const ::my_service::QuadraticSolutionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_service::QuadraticSolutionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct QuadraticSolutionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_service::QuadraticSolutionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_service::QuadraticSolutionResponse_<ContainerAllocator>& v)
  {
    s << indent << "result[]" << std::endl;
    for (size_t i = 0; i < v.result.size(); ++i)
    {
      s << indent << "  result[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.result[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_SERVICE_MESSAGE_QUADRATICSOLUTIONRESPONSE_H
